=== opena11y/fae1-django/fae/dtd/messages.dtd
<!-- messages.dtd -->

<!ENTITY % entities SYSTEM "entities.dtd">
%entities;

<!ELEMENT messages (message+)>

<!ELEMENT message (msg+)>
<!ATTLIST message
	id		ID			#REQUIRED
>

<!ELEMENT msg (#PCDATA | ins | elem | attr)*>
<!ATTLIST msg
	id	(default | pass | warn | fail | null | disc)	#REQUIRED
>

<!--
abbreviations:
	s:	singular
	p:	plural
-->

<!ELEMENT ins (s,p)?>
<!ATTLIST ins
	ref	(%result-id;)	#REQUIRED
>

<!ELEMENT s (#PCDATA | elem | attr)*>
<!ELEMENT p (#PCDATA | elem | attr)*>

<!ELEMENT elem (#PCDATA)>
<!ELEMENT attr (#PCDATA)>

=== opena11y/fae1-django/fae/xml/messages.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE messages SYSTEM "../dtd/messages.dtd">

<messages>

  <!-- NAVIGATION &amp; ORIENTATION -->

  <message id="nav001p">
    <msg id="pass"/>
    <msg id="default">The <attr>lang</attr> attribute value is not a valid language code.</msg>
    <msg id="fail-null">The <attr>lang</attr> attribute was not specified.</msg>
  </message>

  <message id="nav003p">
    <msg id="default">Out of <ins ref="tot1"/> <elem>table</elem> <sp ref="tot1"><s>element</s><p>elements</p></sp>, <ins ref="cnt1"/> <sp ref="cnt1"><s>appears to be a data table</s><p>appear to be data tables</p></sp>. Of those data tables, <ins ref="cnt2"/> <sp ref="cnt2"><s>utilizes</s><p>utilize</p></sp> the <elem>thead</elem> element, and <ins ref="cnt3"/> <sp ref="cnt3"><s>utilizes</s><p>utilize</p></sp> the <elem>th</elem> element.</msg>
    <msg id="disc">No data tables were found.</msg>
  </message>

  <message id="nav004p">
    <msg id="pass"/>
    <msg id="default"><ins ref="cnt1"/> <elem>frame</elem> <sp ref="cnt1"><s>element</s><p>elements</p></sp> (out of <ins ref="tot1"/> total) <sp ref="cnt1"><s>does</s><p>do</p></sp> not meet the criteria.</msg>
    <msg id="disc">No <elem>frame</elem> elements were found.</msg>
  </message>

  <message id="nav005p">
    <msg id="pass"/>
    <msg id="default"><ins ref="cnt1"/> <elem>frameset</elem> <sp ref="cnt1"><s>element does</s><p>elements do</p></sp> not meet the criteria.</msg>
    <msg id="disc">No <elem>frameset</elem> elements were found.</msg>
  </message>

  <message id="nav010p">
    <msg id="pass"/>
    <msg id="fail"><ins ref="cnt1"/> <elem>title</elem> <sp ref="cnt1"><s>element is</s><p>elements are</p></sp> empty.</msg>
    <msg id="disc">No <elem>title</elem> elements were found.</msg>
  </message>

  <message id="nav011p">
    <msg id="pass"/>
    <msg id="default"><ins ref="cnt1"/> <elem>title</elem> <sp ref="cnt1"><s>element was</s><p>elements were</p></sp> found.</msg>
  </message>

  <message id="nav012s">
    <msg id="default"><ins ref="pct1"/>% of all <elem>title</elem> elements are unique (<ins ref="cnt1"/> out of <ins ref="tot1"/>).</msg>
    <msg id="fail-null">No <elem>title</elem> elements were found.</msg>
  </message>

  <message id="nav020p">
    <msg id="pass"/>
    <msg id="fail"><ins ref="cnt1"/> <elem>h1</elem> <sp ref="cnt1"><s>element is</s><p>elements are</p></sp> empty.</msg>
    <msg id="fail-null">No <elem>h1</elem> elements were found.</msg>
  </message>

  <message id="nav021p">
    <msg id="pass"/>
    <msg id="warn"><ins ref="cnt1"/> <elem>h1</elem> <sp ref="cnt1"><s>element is</s><p>elements are</p></sp> empty.</msg>
    <msg id="warn-null">No <elem>h1</elem> elements were found.</msg>
  </message>

  <message id="nav022p">
    <msg id="pass"/>
    <msg id="fail"><ins ref="cnt1"/> <elem>h1</elem> <sp ref="cnt1"><s>element was</s><p>elements were</p></sp> found.</msg>
    <msg id="fail-null">No <elem>h1</elem> elements were found.</msg>
  </message>

  <message id="nav023p">
    <msg id="pass"/>
    <msg id="warn"><ins ref="cnt1"/> <elem>h1</elem> <sp ref="cnt1"><s>element was</s><p>elements were</p></sp> found.</msg>
    <msg id="warn-null">Due to missing elements (0 <elem>h1</elem> elements).</msg>
  </message>

  <message id="nav024p">
    <msg id="pass"/>
    <msg id="warn"><ins ref="cnt1"/> <elem>h1</elem> <sp ref="cnt1"><s>element does</s><p>elements do</p></sp> not meet the criteria.</msg>
    <msg id="warn-null">Due to missing elements (<ins ref="tot1"/> <elem>h1</elem> <sp ref="tot1"><s>element</s><p>elements</p></sp> and <ins ref="tot2"/> <elem>title</elem> <sp ref="tot2"><s>element</s><p>elements</p></sp>).</msg>
  </message>

  <message id="nav030p">
    <msg id="pass"/>
    <msg id="fail"><ins ref="cnt1"/> subheading <sp ref="cnt1"><s>element is</s><p>elements are</p></sp> empty.</msg>
    <msg id="disc">No subheading elements were found.</msg>
  </message>

  <message id="nav031p">
    <msg id="pass"/>
    <msg id="warn"><ins ref="cnt1"/> subheading <sp ref="cnt1"><s>element is</s><p>elements are</p></sp> empty.</msg>
    <msg id="disc">No subheading elements were found.</msg>
  </message>

  <message id="nav032p">
    <msg id="pass"/>
    <msg id="fail">Of the <ins ref="tot1"/> subheading <sp ref="tot1"><s>element that follows</s><p>elements that follow</p></sp> the last <elem>h1</elem> element, <ins ref="cnt1"/> <sp ref="cnt1"><s>is</s><p>are</p></sp> improperly nested.</msg>
    <msg id="fail-null">Improper nesting of subheading elements due to lack of an <elem>h1</elem> element.</msg>
    <msg id="disc">No nested subheading elements were found.</msg>
  </message>

  <message id="nav041p">
    <msg id="pass"/>
    <msg id="warn"><ins ref="cnt1"/> <elem>ul</elem> or <elem>ol</elem> <sp ref="cnt1"><s>element</s><p>elements</p></sp> (out of <ins ref="tot1"/> total) <sp ref="cnt1"><s>does</s><p>do</p></sp> not meet the criteria.</msg>
    <msg id="disc">No <elem>ul</elem> or <elem>ol</elem> elements that appear to be navigation bars were found.</msg>
  </message>

  <message id="nav042p">
    <msg id="pass"/>
    <msg id="warn"><ins ref="cnt1"/> <elem>map</elem> <sp ref="cnt1"><s>element</s><p>elements</p></sp> (out of <ins ref="tot1"/> total) <sp ref="cnt1"><s>does</s><p>do</p></sp> not meet the criteria.</msg>
    <msg id="disc">No <elem>map</elem> elements that appear to be navigation bars were found.</msg>
  </message>

  <message id="nav043p">
    <msg id="pass"/>
    <msg id="warn"><ins ref="cnt1"/> <elem>area</elem> <sp ref="cnt1"><s>element</s><p>elements</p></sp> (<ins ref="pct1"/>% of <ins ref="tot1"/> total) <sp ref="cnt1"><s>does</s><p>do</p></sp> not meet the criteria.</msg>
    <msg id="disc">No <elem>area</elem> elements were found.</msg>
  </message>

  <message id="nav050p">
    <msg id="pass"/>
    <msg id="fail"><ins ref="cnt1"/> <elem>label</elem> <sp ref="cnt1"><s>element</s><p>elements</p></sp> and <ins ref="cnt2"/> <elem>legend</elem> <sp ref="cnt2"><s>element</s><p>elements</p></sp> are empty.</msg>
    <msg id="disc">No <elem>label</elem> or <elem>legend</elem> elements were found.</msg>
  </message>

  <message id="nav051p">
    <msg id="pass"/>
    <msg id="fail"><ins ref="cnt1"/> out of <ins ref="tot1"/> <elem>form</elem> <sp ref="tot1"><s>control</s><p>controls</p></sp> <sp ref="cnt1"><s>does</s><p>do</p></sp> not meet the criteria.</msg>
    <msg id="disc">No <elem>form</elem> controls of the specified types were found.</msg>
  </message>

  <message id="nav052p">
    <msg id="pass"/>
    <msg id="fail"><ins ref="cnt1"/> out of <ins ref="tot1"/> <elem>form</elem> <sp ref="tot1"><s>control does</s><p>controls do</p></sp> not meet the criteria.</msg>
    <msg id="disc">No <elem>form</elem> controls of the specified types were found.</msg>
  </message>

  <message id="nav053p">
    <msg id="pass"/>
    <msg id="fail"><ins ref="cnt1"/> <elem>form</elem> <sp ref="cnt1"><s>control</s><p>controls</p></sp> (out of <ins ref="tot1"/> total) <sp ref="cnt1"><s>does</s><p>do</p></sp> not meet the criteria.</msg>
    <msg id="disc">No <elem>form</elem> controls of the specified type were found.</msg>
  </message>

  <!-- TEXT EQUIVALENTS -->

  <message id="text001p">
    <msg id="default"><ins ref="pct1"/>% (<ins ref="cnt1"/> out of <ins ref="tot1"/>)</msg>
    <msg id="disc">No <elem>img</elem> elements were found.</msg>
  </message>

  <message id="text002p">
    <msg id="default"><ins ref="pct1"/>% (<ins ref="cnt1"/> out of <ins ref="tot1"/>)</msg>
    <msg id="disc">No <elem>embed</elem> elements were found.</msg>
  </message>

  <message id="text003p">
    <msg id="default"><ins ref="pct1"/>% (<ins ref="cnt1"/> out of <ins ref="tot1"/>)</msg>
    <msg id="disc">No <elem>applet</elem> elements were found.</msg>
  </message>

  <message id="text004p">
    <msg id="default"><ins ref="pct1"/>% (<ins ref="cnt1"/> out of <ins ref="tot1"/>)</msg>
    <msg id="disc">No <elem>object</elem> elements were found.</msg>
  </message>

  <message id="text005p">
    <msg id="default"><ins ref="pct1"/>% (<ins ref="cnt1"/> out of <ins ref="tot1"/>)</msg>
    <msg id="disc">No <elem>img</elem> elements were found.</msg>
  </message>

  <message id="text006p">
    <msg id="default"><ins ref="pct1"/>% (<ins ref="cnt1"/> out of <ins ref="tot1"/>)</msg>
    <msg id="disc">No <elem>img</elem> elements with an <attr>alt</attr> attribute were found.</msg>
  </message>

  <!-- SCRIPTING &amp; AUTOMATION -->

  <message id="auto001p">
    <msg id="default"><ins ref="pct1"/>% (<ins ref="cnt1"/> out of <ins ref="tot1"/>)</msg>
    <msg id="disc">No elements with an <attr>onmouseover</attr> attribute were found.</msg>
  </message>

  <message id="auto002p">
    <msg id="default"><ins ref="pct1"/>% (<ins ref="cnt1"/> out of <ins ref="tot1"/>)</msg>
    <msg id="disc">No elements with an <attr>onmouseout</attr> attribute were found.</msg>
  </message>

  <!-- STYLING -->

  <message id="style001p">
    <msg id="default"><ins ref="pct1"/>% of the content on the page is styled using deprecated HTML elements.</msg>
    <msg id="null">No deprecated style elements were found.</msg>
  </message>

  <message id="style002p">
    <msg id="default"><ins ref="cnt1"/> nested <sp ref="cnt1"><s>table was</s><p>tables were</p></sp> found out of <ins ref="tot1"/> <elem>table</elem> <sp ref="tot1"><s>element</s><p>elements</p></sp>, with a maximum depth of <ins ref="r1"/>.</msg>
    <msg id="disc">No <elem>table</elem> elements were found.</msg>
  </message>

  <message id="style003p">
    <msg id="pass">No images appear to be stylistic based on their dimensions (having a width or height of less than 4 pixels). <ins ref="cnt2"/> out of <ins ref="tot1"/> images were retrieved and analyzed.</msg>
    <msg id="warn">No images appear to be decorative based on their dimensions (having a width or height of less than 4 pixels). However, not all images (<ins ref="cnt2"/> out of <ins ref="tot1"/>) were retrieved and analyzed.</msg>
