=== opena11y/fae1-django/fae/dtd/testdoc.dtd
<!-- testdoc.dtd -->

<!ELEMENT testdoc (section+)>

<!ELEMENT section (name, info*, category+, link*)>
<!ATTLIST section
    id      (nav|text|auto|style|std)    #REQUIRED
>

<!ELEMENT category (name, info*, best-practice+, link*)>
<!ATTLIST category
    id      CDATA          #REQUIRED
>

<!ELEMENT best-practice (name, rule, info*, (page | site)+, link*)>
<!ATTLIST best-practice
    ref     CDATA          #REQUIRED
    new     CDATA          #IMPLIED
>

<!ELEMENT page EMPTY>
<!ATTLIST page
    id      CDATA          #REQUIRED
>

<!ELEMENT site EMPTY>
<!ATTLIST site
    id      CDATA          #REQUIRED
>

<!ELEMENT name (#PCDATA)>
<!ELEMENT rule (#PCDATA | elem | attr)*>
<!ELEMENT info (#PCDATA | elem | attr)*>

<!ELEMENT elem (#PCDATA)>
<!ELEMENT attr (#PCDATA)>

=== opena11y/fae1-django/fae/xml/testdoc.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE testdoc SYSTEM "../dtd/testdoc.dtd">

<testdoc>

  <!-- ================================================ -->
  <section id="nav">
    <name>Navigation &amp; Orientation</name>

    <!-- ================================================ -->
    <category id="titles">
      <name>Titles (<elem>title</elem> &amp; <elem>h1</elem>)</name>

      <best-practice ref="nav011" new="1.0.b1">
        <name>one and only one title</name>
        <rule>The page must contain exactly one <elem>title</elem> element.</rule>
        <page id="nav011p"/>
        <site id="nav011s"/>
      </best-practice>

      <best-practice ref="nav010" new="1.0.b1">
        <name>number of empty title elements</name>
        <rule>The <elem>title</elem> element must have text content.</rule>
        <page id="nav010p"/>
        <site id="nav010s"/>
      </best-practice>

      <best-practice ref="nav022" new="1.0.b1">
        <name>at least one h1 element</name>
        <rule>The page must contain at least one <elem>h1</elem> element.</rule>
        <page id="nav022p"/>
        <site id="nav022s"/>
      </best-practice>

      <best-practice ref="nav023" new="1.0.b1">
        <name>no more than two h1 elements</name>
        <rule>The page should contain no more than two <elem>h1</elem> elements.</rule>
        <page id="nav023p"/>
        <site id="nav023s"/>
      </best-practice>

      <best-practice ref="nav024" new="1.0.b2">
        <name>h1 substring of title</name>
        <rule>The text content of each <elem>h1</elem> element should match all or part of the <elem>title</elem> content.</rule>
        <info>The matching algorithm for this rule includes the <attr>alt</attr> text of any <elem>img</elem> elements the <elem>h1</elem> may contain, and ignores case, punctuation and spacing in the text content of the <elem>title</elem> and <elem>h1</elem> elements.</info>
        <page id="nav024p"/>
        <site id="nav024s"/>
      </best-practice>

      <best-practice ref="nav020" new="1.0.b2">
        <name>number of empty h1 elements, including img alt text</name>
        <rule>Each <elem>h1</elem> element must have text content.</rule>
        <info>If an <elem>img</elem> element with an <attr>alt</attr> attribute is contained in an <elem>h1</elem> element, the <attr>alt</attr> attribute value is inserted in document order into the text content of the <elem>h1</elem> element.</info>
        <page id="nav020p"/>
        <site id="nav020s"/>
      </best-practice>

      <best-practice ref="nav021" new="1.0.b2">
        <name>number of empty h1 elements, excluding img alt text</name>
        <rule>Each <elem>h1</elem> element should have text content exclusive of the <attr>alt</attr> text of any <elem>img</elem> elements it contains.</rule>
        <page id="nav021p"/>
        <site id="nav021s"/>
      </best-practice>

      <link tgt="bp" href="nav/title/"/>
    </category>

    <!-- ================================================ -->
    <category id="subheadings">
      <name>Subheadings (<elem>h2</elem>..<elem>h6</elem>)</name>

      <best-practice ref="nav032" new="1.0.b1">
        <name>proper nesting of heading elements</name>
        <rule>Subheading elements that follow the last <elem>h1</elem> should be properly nested.</rule>
        <info>Subheading elements should be used without skipping levels when descending through the sublevels <elem>h2</elem>..<elem>h6</elem>. For example, an <elem>h2</elem> element should follow an <elem>h1</elem> element, an <elem>h3</elem> element should follow an <elem>h2</elem> element, and so on. Note that this rule does not apply to subheadings of the same level (for example, an <elem>h3</elem> may follow another <elem>h3</elem>), or when ascending the hierarchy (an <elem>h2</elem> may follow an <elem>h4</elem>).</info>
        <page id="nav032p"/>
        <site id="nav032s"/>
      </best-practice>

      <best-practice ref="nav030" new="1.0.b2">
        <name>number of empty heading elements, including alt text</name>
        <rule>Each subheading element (<elem>h2</elem>..<elem>h6</elem>) must have text content.</rule>
        <info>If an <elem>img</elem> element with an <attr>alt</attr> attribute is contained in a subheading element, the <attr>alt</attr> attribute value is inserted in document order into the text content of the subheading element.</info>
        <page id="nav030p"/>
        <site id="nav030s"/>
      </best-practice>

      <best-practice ref="nav031" new="1.0.b2">
        <name>number of empty heading elements, excluding alt text</name>
        <rule>Each subheading element (<elem>h2</elem>..<elem>h6</elem>) should have text content exclusive of the <attr>alt</attr> text of any <elem>img</elem> elements it contains.</rule>
        <page id="nav031p"/>
        <site id="nav031s"/>
      </best-practice>

      <link tgt="bp" href="nav/heading/"/>
    </category>

    <!-- ================================================ -->
    <category id="nav-bars">
      <name>Navigation Bars</name>

      <best-practice ref="nav041" new="1.0.b5">
        <name>ul/ol navigation menus</name>
        <rule>Each <elem>ul</elem> or <elem>ol</elem> element that precedes the last <elem>h1</elem> element and appears to be a navigation bar should be immediately preceded by a heading element, preferably an <elem>h2</elem>.</rule>
        <info>FAE considers a <elem>ul</elem> or <elem>ol</elem> element to be a navigation bar if it appears to be a navigation list, defined recursively as follows. A navigation list is a <elem>ul</elem> or <elem>ol</elem> element that contains one or more &quot;item with link&quot; <elem>li</elem> elements, and no more than one <elem>li</elem> element that does not qualify as an &quot;item with link&quot;. An &quot;item with link&quot; is defined as an <elem>li</elem> element that contains either a single text link (<elem>a</elem> element) or a link followed by a nested navigation list, optionally preceded by a heading element.</info>
        <page id="nav041p"/>
        <site id="nav041s"/>
      </best-practice>

      <best-practice ref="nav042" new="1.0.b5">
        <name>map navigation bars</name>
        <rule>Each <elem>map</elem> element that precedes the last <elem>h1</elem> element and appears to be a navigation bar should be immediately preceded by a heading element, preferably an <elem>h2</elem></rule>
        <info>FAE considers a <elem>map</elem> element to be a navigation bar if it contains one or more <elem>area</elem> elements.</info>
        <page id="nav042p"/>
        <site id="nav042s"/>
      </best-practice>

      <best-practice ref="nav043" new="1.0.b3">
        <name>redundant text links for area elements</name>
        <rule>Each <elem>area</elem> element should have a redundant text link (<elem>a</elem> element) with matching <attr>href</attr> value.</rule>
        <page id="nav043p"/>
        <site id="nav043s"/>
      </best-practice>

      <link tgt="bp" href="nav/menu/"/>
    </category>

    <!-- ================================================ -->
    <category id="form-labels">
      <name>Form Control Labels</name>

      <best-practice ref="nav051" new="1.0.b1">
        <name>form control labels for select, textarea and input elements</name>
        <rule>Each <elem>input</elem> element with <attr>type=text</attr> | <attr>password</attr> | <attr>checkbox</attr> | <attr>radio</attr> | <attr>file</attr> and each <elem>select</elem> and <elem>textarea</elem> element must either be referenced by the <attr>for</attr> attribute of a <elem>label</elem> element via its <attr>id</attr> attribute, or have a <attr>title</attr> attribute.</rule>
        <info>Label referencing is implemented by setting the <elem>label</elem> element's <attr>for</attr> attribute value equal to that of the <elem>form</elem> control's <attr>id</attr> attribute.</info>
        <page id="nav051p"/>
        <site id="nav051s"/>
      </best-practice>

      <best-practice ref="nav052" new="1.0.b1">
        <name>form control labels for input elements with type=button|reset|submit</name>
        <rule>Each <elem>input</elem> element with <attr>type=button</attr> | <attr>submit</attr> | <attr>reset</attr> must have either a <attr>value</attr> attribute or a <attr>title</attr> attribute.</rule>
        <page id="nav052p"/>
        <site id="nav052s"/>
      </best-practice>

      <best-practice ref="nav053" new="1.0.b2">
        <name>form control labels for input elements with type=image</name>
        <rule>Each <elem>input</elem> element with <attr>type=image</attr> must have either an <attr>alt</attr> attribute or a <attr>title</attr> attribute.</rule>
        <page id="nav053p"/>
        <site id="nav053s"/>
      </best-practice>

      <best-practice ref="nav050" new="1.0.b3">
        <name>label and legend elements must not be empty</name>
        <rule>Each <elem>label</elem> and <elem>legend</elem> element must have text content.</rule>
        <page id="nav050p"/>
        <site id="nav050s"/>
      </best-practice>

      <link tgt="bp" href="nav/form/"/>
    </category>

    <!-- ================================================ -->
    <category id="language">
      <name>Default Language</name>

      <best-practice ref="nav001" new="1.0.b4">
        <name>html@lang attribute</name>
        <rule>Each page must have a <attr>lang</attr> attribute on its <elem>html</elem> element whose value or initial subtag is a valid two-character language code.</rule>
        <info>Valid two-character language codes are defined in the IANA Language Subtag Registry. If the <attr>lang</attr> attribute value is hyphenated, then the substring preceding the first hyphen is tested for validity.</info>
        <page id="nav001p"/>
        <site id="nav001s"/>
      </best-practice>

      <link tgt="bp" href="nav/lang/"/>
    </category>

    <!-- ================================================ -->
